"""add hints column to questions

Revision ID: 538a96c3ac79
Revises: 32af4bea45b6
Create Date: 2026-08-21 09:19:06.013316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538a96c3ac79'
down_revision: Union[str, Sequence[str], None] = '32af4bea45b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('hints', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'hints')
    # ### end Alembic commands ###
